version: '3.9'

networks:
  red-service:
    name: red-service

services:
  app-red:
    image: webdevops/php-nginx:8.2
    container_name: app-red
    #    user: application:application
    restart: on-failure
    working_dir: /app
    ports:
      - 80:80
    volumes:
      - .:/app:rw
    environment:
      - WEB_DOCUMENT_ROOT=/app/public    
    networks:
      - red-service
  nginx:
      image: 'jc21/nginx-proxy-manager:latest'
      container_name: nginx
      restart: unless-stopped
      ports:
        - '80:80'
        - '8080:81'
        - '443:443'
      volumes:
        - ./data:/data
        - ./letsencrypt:/etc/letsencrypt
      networks:
        - red-service